# Modelo de Classificação

## 1. Objetivo do modelo

## 2. Setup e carga dos dados processados

## 3. Preparação para modelagem

## 4. Modelagem Supervisionada - Classificação

### 4.1 Baseline (modelo trivial para referência)

### 4.2 Modelo 1 - XXXXXXX

### 4.3 Modelo 2 - XXXX

### 4.4 Comparação dos Modelos

## 5. Modelagem não supervisionada

### 5.1 Objetivo da análise

### 5.2 Aplicação (clusterização ou PCA)

### 5.3 Interpretaçãodos resultados

## 6. Apresentação Crítica

### 6.1 Apresentação crítica

### 6.2 Limitações dos modelos

### 6.3 Próximos passos

In [1]:
# Importando bibliotecas necessárias.
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from src import data_loader

In [2]:
df_raw = pd.read_csv('../data/raw/flights.csv')
df_raw['ORIGIN_AIRPORT'].isna().sum()

/tmp/ipykernel_21456/3459974131.py:1: DtypeWarning: Columns (0: ORIGIN_AIRPORT, 1: DESTINATION_AIRPORT) have mixed types. Specify dtype option on import or set low_memory=False.
  df_raw = pd.read_csv('../data/raw/flights.csv')

np.int64(0)

In [4]:
df_raw['ORIGIN_AIRPORT'].apply(type).value_counts()

ORIGIN_AIRPORT
<class 'str'>    5360327
<class 'int'>     458752
Name: count, dtype: int64

In [2]:
df = data_loader.load_flights('../data/raw/flights.csv', output_path='../data/processed/flights_class2.parquet')
df.info()

/home/grazzica/ProjetosPosML/Tech_challenge_3/src/data_loader.py:12: DtypeWarning: Columns (0: ORIGIN_AIRPORT, 1: DESTINATION_AIRPORT) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_path)

<class 'pandas.DataFrame'>
Index: 5231130 entries, 0 to 5819078
Data columns (total 11 columns):
 #   Column                      Dtype
---  ------                      -----
 0   MONTH                       int64
 1   DAY                         int64
 2   DAY_OF_WEEK                 int64
 3   AIRLINE                     str
 4   ORIGIN_AIRPORT              object
 5   DESTINATION_AIRPORT         object
 6   DISTANCE                    int64
 7   ARRIVAL_DELAY               float64
 8   SCHEDULED_DEPARTURE_HOUR    int64
 9   SCHEDULED_DEPARTURE_MINUTE  int64
 10  ARRIVAL_DELAY_CLASS         int64
dtypes: float64(1), int64(7), object(2), str(1)
memory usage: 489.5+ MB

In [3]:
df.info()

<class 'pandas.DataFrame'>
Index: 5231130 entries, 0 to 5819078
Data columns (total 11 columns):
 #   Column                      Dtype
---  ------                      -----
 0   MONTH                       int64
 1   DAY                         int64
 2   DAY_OF_WEEK                 int64
 3   AIRLINE                     str
 4   ORIGIN_AIRPORT              object
 5   DESTINATION_AIRPORT         object
 6   DISTANCE                    int64
 7   ARRIVAL_DELAY               float64
 8   SCHEDULED_DEPARTURE_HOUR    int64
 9   SCHEDULED_DEPARTURE_MINUTE  int64
 10  ARRIVAL_DELAY_CLASS         int64
dtypes: float64(1), int64(7), object(2), str(1)
memory usage: 489.5+ MB

In [ ]:
df = pd.read_parquet('../data/processed/flights_class.parquet')
df.info()

<class 'pandas.DataFrame'>
Index: 5231130 entries, 0 to 5819078
Data columns (total 11 columns):
 #   Column                      Dtype
---  ------                      -----
 0   MONTH                       int64
 1   DAY                         int64
 2   DAY_OF_WEEK                 int64
 3   AIRLINE                     str
 4   ORIGIN_AIRPORT              str
 5   DESTINATION_AIRPORT         str
 6   DISTANCE                    int64
 7   ARRIVAL_DELAY               float64
 8   SCHEDULED_DEPARTURE_HOUR    int64
 9   SCHEDULED_DEPARTURE_MINUTE  int64
 10  ARRIVAL_DELAY_CLASS         int64
dtypes: float64(1), int64(7), str(3)
memory usage: 518.8 MB

In [6]:
from sklearn.preprocessing import LabelEncoder

codificador_airline = LabelEncoder()
df['AIRLINE'] = codificador_airline.fit_transform(df['AIRLINE'])    

display(df.head())

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DISTANCE,ARRIVAL_DELAY,SCHEDULED_DEPARTURE_HOUR,SCHEDULED_DEPARTURE_MINUTE,ARRIVAL_DELAY_CLASS
0,1,1,4,1,ANC,SEA,1448,-22.0,0,5,0
1,1,1,4,0,LAX,PBI,2330,-9.0,0,10,0
2,1,1,4,11,SFO,CLT,2296,5.0,0,20,0
3,1,1,4,0,LAX,MIA,2342,-9.0,0,20,0
4,1,1,4,1,SEA,ANC,1448,-21.0,0,25,0

In [7]:

df['ORIGIN_AIRPORT'] = df['ORIGIN_AIRPORT'].fillna('UNKNOWN').astype(str).str.strip()
codificador_origin_airport = LabelEncoder()
df['ORIGIN_AIRPORT'] = codificador_origin_airport.fit_transform(df['ORIGIN_AIRPORT'])
display(df.head())

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DISTANCE,ARRIVAL_DELAY,SCHEDULED_DEPARTURE_HOUR,SCHEDULED_DEPARTURE_MINUTE,ARRIVAL_DELAY_CLASS
0,1,1,4,1,17,SEA,1448,-22.0,0,5,0
1,1,1,4,0,176,PBI,2330,-9.0,0,10,0
2,1,1,4,11,278,CLT,2296,5.0,0,20,0
3,1,1,4,0,176,MIA,2342,-9.0,0,20,0
4,1,1,4,1,277,ANC,1448,-21.0,0,25,0

In [8]:
df['DESTINATION_AIRPORT'] = df['DESTINATION_AIRPORT'].fillna('UNKNOWN').astype(str).str.strip()
codificador_destination_airport = LabelEncoder()
df['DESTINATION_AIRPORT'] = codificador_destination_airport.fit_transform(df['DESTINATION_AIRPORT'])
display(df.head())

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DISTANCE,ARRIVAL_DELAY,SCHEDULED_DEPARTURE_HOUR,SCHEDULED_DEPARTURE_MINUTE,ARRIVAL_DELAY_CLASS
0,1,1,4,1,17,277,1448,-22.0,0,5,0
1,1,1,4,0,176,235,2330,-9.0,0,10,0
2,1,1,4,11,278,66,2296,5.0,0,20,0
3,1,1,4,0,176,203,2342,-9.0,0,20,0
4,1,1,4,1,277,17,1448,-21.0,0,25,0

In [9]:
df2 = df.drop(columns=['ARRIVAL_DELAY'])
y = df2['ARRIVAL_DELAY_CLASS']
x = df2.drop(columns=['ARRIVAL_DELAY_CLASS'])

In [10]:
# treinar o modelo de machine learning
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# Criar o modelo de machine learning
modelo_arvore_decisao = RandomForestClassifier(random_state=42, n_jobs = 6)
#modelo_knn = KNeighborsClassifier()

# Treinar o modelo de machine learning
modelo_arvore_decisao.fit(x_train, y_train)